<script src="bootstrap/js/jquery.lbslider.js"></script> 
<div class="slider">
    <div class="vague"></div>
    <div class="slide-item slide-1">
        <div class="container" style="position: relative">
            
            <div class="txt">
                <h1>GRAPHIC DESIGN</h1><br>
                <h3>Your ideas will be realistic</h3><br>
                <ul>
                    <li>Visual identity</li>
                    <li>Logo Design</li>
                    <li>Industrial Design</li>
                    <li>Vehicule Dressing</li>
                    <li>Packaging Creation</li>
                </ul>
            </div>
            
            <div class="sl-img">
                <img src="images/sliderimg-1.png"/>
            </div>
        </div>
    </div>
    <div class="slide-item slide-2">
        <div class="container" style="position: relative">
            
            <div class="txt">
                <h1>Marketing</h1><br>
                <h3>We boost your brand</h3><br>
                <ul>
                    <li>Newsletter & Emailing</li>
                    <li>Website SEO</li>
                    <li>Street Marketing</li>
                    <li>Entreprise Value</li>
                    <li>Compaign Management</li>
                </ul>
            </div>
            
            <div class="sl-img">
                <img src="images/sliderimg-2.png"/>
            </div>
        </div>
    </div>
</div>
<div class="vague-white">
</div>
<div class="content home">
  <div class="container">
  	<div class="col-lg-12 home-service">
  		<div class="col-lg-4 ser com">
  			<img src="images/com_for_website.gif" />
 			<h2>Communication</h2>
 			<p><em>Post hoc impie perpetratum quod in aliis quoque iam.</em></p>
  		</div>
  		<div class="col-lg-4 ser events">
  			<img src="images/events_for_website.gif" />
 			<h2>Événementiel</h2>
 			<p><em>Post hoc impie perpetratum quod in aliis quoque iam.</em></p>
  		</div>
  		<div class="col-lg-4 ser audiovis">
  			<img src="images/audiovisuel_for_website.gif" />
 			<h2>Production Audiovisuelle</h2>
 			<p><em>Post hoc impie perpetratum quod in aliis quoque iam.</em></p>
  		</div>
  	</div>
  </div>
  <div class="container">
  	<div class="partner">
  		<div class="slider-wrap">
			<div class="carousel">
				<ul>
					<li> <span class="partner1"></span> </li>
					<li> <span class="partner2"></span> </li>
					<li> <span class="partner3"></span> </li>
					<li> <span class="partner4"></span> </li>
					<li> <span class="partner5"></span> </li>
				</ul>
			</div>
			<a href="#" class="slider-arrow sa-left"><img src="images/arrow_left-partner.png" /></a> 
			<a href="#" class="slider-arrow sa-right"><img src="images/arrow_right-partner.png" /></a> 
		</div>
		<script>
			jQuery('.carousel').lbSlider({
			    leftBtn: '.sa-left',
			    rightBtn: '.sa-right',
			    visible: 4,
			    autoPlay: true,
			    autoPlayDelay: 3
			});
		</script>
  	</div>
  </div>
</div>
