<div class="page-title">
  <div class="vague2"></div>
  <div class="container">
  	<h2 class="title">TÉMOIGNAGE</h2>
  </div>
</div>
<div class="content temoignage">
  <div class="container">
  	<div class="col-lg-3">
  	   <center><img src="images/universal.png" /></center>
  	</div>
  	<div class="col-lg-8">
  		<h2>Universal Music Group</h2>
        <p>Hac ita persuasione reducti intra moenia bellatores obseratis undique portarum aditibus, propugnaculis insistebant et pinnis, congesta undique saxa telaque habentes in promptu, ut si quis se proripuisset interius, multitudine missilium sterneretur et lapidum.
        </p>
        <p>Et licet quocumque oculos flexeris feminas adfatim multas spectare cirratas, quibus, si nupsissent, per aetatem ter iam nixus poterat suppetere liberorum, ad usque taedium pedibus pavimenta tergentes iactari volucriter gyris, dum exprimunt innumera simulacra, quae finxere fabulae theatrales.</p>
  	</div>
  </div>
  <div class="container">
  	<div class="col-lg-3">
  	   <center><img src="images/voice.png" /></center>
  	</div>
  	<div class="col-lg-8">
  		<h2>Voice Media</h2>
        <p>Hac ita persuasione reducti intra moenia bellatores obseratis undique portarum aditibus, propugnaculis insistebant et pinnis, congesta undique saxa telaque habentes in promptu, ut si quis se proripuisset interius, multitudine missilium sterneretur et lapidum.
        </p>
        <p>Et licet quocumque oculos flexeris feminas adfatim multas spectare cirratas, quibus, si nupsissent, per aetatem ter iam nixus poterat suppetere liberorum, ad usque taedium pedibus pavimenta tergentes iactari volucriter gyris, dum exprimunt innumera simulacra, quae finxere fabulae theatrales.</p>
  	</div>
  </div>
  <div class="container">
  	<div class="col-lg-3">
  	   <center><img src="images/noubal.png" /></center>
  	</div>
  	<div class="col-lg-8">
  		<h2>Noubal Media</h2>
        <p>Hac ita persuasione reducti intra moenia bellatores obseratis undique portarum aditibus, propugnaculis insistebant et pinnis, congesta undique saxa telaque habentes in promptu, ut si quis se proripuisset interius, multitudine missilium sterneretur et lapidum.
        </p>
        <p>Et licet quocumque oculos flexeris feminas adfatim multas spectare cirratas, quibus, si nupsissent, per aetatem ter iam nixus poterat suppetere liberorum, ad usque taedium pedibus pavimenta tergentes iactari volucriter gyris, dum exprimunt innumera simulacra, quae finxere fabulae theatrales.</p>
  	</div>
  </div>
</div>

