<div class="page-title">
  <div class="vague2"></div>
  <div class="container">
  	<h2 class="title">Our services</h2>
  </div>
</div>
<div class="content services">
  <div class="container commuication">
  	<div class="col-lg-5">
  	   <center><img src="images/communication-service.png" /></center>
  	</div>
  	<div class="col-lg-7">
  	   <center>
          <p>Créé en 2014 MEDIA TUCH est une agence de communication et événementiel dont l’activité est dédiée à la conception et la mise en œuvre de projets évènementiels et de communication responsables à destination des entreprises et des collectivités.
          </p>
          <p>Grâce à son équipe jeune, pluridisciplinaire, dynamique et créative, MEDIA TUCH propose une gestion efficace et novatrice de vos besoins en communication. Elle vous accompagne dans la réussite de vos enjeux.</p>
          <br><br>
          <a id="service-detail" href="communication">EN SAVOIR +</a>
       </center>
  	</div>
  </div>
  <div class="container event">
    <div class="col-lg-7">
       <center>
          <p>Créé en 2014 MEDIA TUCH est une agence de communication et événementiel dont l’activité est dédiée à la conception et la mise en œuvre de projets évènementiels et de communication responsables à destination des entreprises et des collectivités.
          </p>
          <p>Grâce à son équipe jeune, pluridisciplinaire, dynamique et créative, MEDIA TUCH propose une gestion efficace et novatrice de vos besoins en communication. Elle vous accompagne dans la réussite de vos enjeux.</p>
          <br><br><br>
          <a id="service-detail" href="event">EN SAVOIR +</a>
       </center>
    </div>
        <div class="col-lg-5">
       <center><img src="images/event-service.png" /></center>
    </div>
  </div>
  <div class="container audiovisu">
    <div class="col-lg-5">
       <center><img src="images/audiovisu-service.png" /></center>
    </div>
    <div class="col-lg-7">
       <center>
          <p>Créé en 2014 MEDIA TUCH est une agence de communication et événementiel dont l’activité est dédiée à la conception et la mise en œuvre de projets évènementiels et de communication responsables à destination des entreprises et des collectivités.
          </p>
          <p>Grâce à son équipe jeune, pluridisciplinaire, dynamique et créative, MEDIA TUCH propose une gestion efficace et novatrice de vos besoins en communication. Elle vous accompagne dans la réussite de vos enjeux.</p>
          <br><br><br>
          <a id="service-detail" href="audiovisu">EN SAVOIR +</a>
       </center>
    </div>
  </div>
</div>

