<html>
	<head>
		<title>MEDIATUCH</title>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<meta name="viewport" content="initial-scale=1">
		<!-- Latest compiled and minified CSS -->
		<link rel="stylesheet" href="bootstrap/css/bootstrap.min.css">

		<!-- Optional theme -->
		<link rel="stylesheet" href="bootstrap/css/bootstrap-theme.min.css">
		<link rel="stylesheet" href="css/jquery.popup.css">
		<link rel="stylesheet" href="css/modal-videos.css">
		<!-- Main Style -->
		

		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

		<!-- Jquery -->
		<script src="bootstrap/js/jquery.min.js"></script>
		<!-- Latest compiled and minified JavaScript -->
		<script src="bootstrap/js/bootstrap.min.js"></script>

		<script src="bootstrap/js/jquery.cycle.all.min.js"></script>
		<script src="bootstrap/js/setup.js"></script>
		<script src="bootstrap/js/newfunctions.js"></script>

		<link rel="shortcut icon" href="images/ico-fatin.png" type="image/x-icon"> 
		<link rel="stylesheet" href="css/style.css">

		<link href="flat/yellow.css" rel="stylesheet">
		<script src="bootstrap/js/icheck.js"></script>
		<script src="bootstrap/js/isotope.pkgd.min.js"></script>
		<script src="bootstrap/js/modal-videos.js"></script>
        
        <script src="js/main.js"></script>
		<!--<style type="text/css">
			@import url(http://fonts.googleapis.com/earlyaccess/droidarabickufi.css);
		</style>-->

	</head>
	<body>
		<header>
			<nav class="navbar header-cont">
      			<div class="container">
			        <div class="navbar-header">
			          	<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
			            	<span class="sr-only">Toggle navigation</span>
			            	<span class="icon-bar"></span>
			            	<span class="icon-bar"></span>
			            	<span class="icon-bar"></span>
			          	</button> 
			          	<a class="navbar-brand" href="/projects/MediaTuch/public/"><img src="images/logo.png"/></a>
			        </div>
	        		<div id="navbar" class="navbar-collapse collapse">
	          			<ul id="main-menu" class="nav navbar-nav menu" >
							<li class="<?= $this->portfolio ?>"><a href="portfolio">Portfolio</a></li>
							<li class=""><a href="about">Events</a></li>
							</script>
							<li class="parent">
								<a href="">Media Tuch</a>
								<ul class="sub-menu">
									<li><a href="about">How are we?</a></li>
									<li><a href="services">Our Service</a></li>
									<li><a href="">Our Team</a></li>
									<li><a href="witness">Witness</a></li>
								</ul> 
							</li>
							<li><a href="#">Blog</a></li>
							<li class="<?= $this->contact ?>"><a href="contact">Contact</a></li>
							<li><a id="language-selector" href="#"><img src="images/FR-Flag.png" /></a></li>
						</ul> 
	        		</div>
      			</div>
    		</nav>
		</header>
		<?php echo $this->layout()->content; ?>	
		<footer>
			<div class="prescription">
				<div class="container">
					<div class="col-lg-12">
						<h3>Need a prescription?</h3>
						<a href="#"><img id="needprescription" src="images/needprescription.jpg" /></a>
					</div>
				</div>
			</div>
			<div class="foot">
				<div class="container">
					<div class="col-lg-12">
					    <div class="col-lg-3">
					      	<h3><span>Follow us !&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></h3>
							<div class="Rsocial">
								<a href="#"><li id="facebook" class="col-lg-2"><img src="images/Facebook_icon.png" /></li></a>
								<a href="#"><li id="twitter" class="col-lg-2"><img src="images/Twitter_icon.png" /></li></a>
								<a href="#"><li id="youtube" class="col-lg-2"><img src="images/Youtube_icon.png" /></li></a>
								<a href="#"><li id="googleplus" class="col-lg-2"><img src="images/Google+_icon.png" /></li></a>
								<a href="#"><li id="linkedin" class="col-lg-2"><img src="images/Linkedin_icon.png" /></li></a>
								<a href="#"><li id="vimeo" class="col-lg-2"><img src="images/Vimeo_icon.png" /></li></a>
								<a href="#"><li id="flicker" class="col-lg-2"><img src="images/Flicker_icon.png" /></li></a>
							</div>
				      	</div>
				      	<div class="col-lg-5 newsletter">
				      		<h3><span>Subscribe on New</span>sletter !</h3>
				      		<h4><em>Subscribe to get our latest offers</em></h4>
				      		<input class="col-lg-8" type="text" id="email" value="Your email here..."/>
				      		<input class="col-lg-3" type="button" id="go" value="Go!"/>
				      	</div>
				      	<div class="col-lg-4">
				      		<h3><span>Suivez-nous sur Fa</span>cebook</h3>
				      		<div id="fb-root"></div>
							<script>(function(d, s, id) {
							  var js, fjs = d.getElementsByTagName(s)[0];
							  if (d.getElementById(id)) return;
							  js = d.createElement(s); js.id = id;
							  js.src = "//connect.facebook.net/fr_FR/sdk.js#xfbml=1&version=v2.6";
							  fjs.parentNode.insertBefore(js, fjs);
							}(document, 'script', 'facebook-jssdk'));</script>
							<div class="fb-page" data-href="https://www.facebook.com/mediatuch" data-tabs="timeline" data-height="215" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"><div class="fb-xfbml-parse-ignore"><blockquote cite="https://www.facebook.com/mediatuch"><a href="https://www.facebook.com/mediatuch">Media Tuch</a></blockquote></div></div>
				      	</div>
				    </div>
				</div>
			</div>	
			<div class="copyright">
				<div class="container">
					<div class="col-lg-4 col-lg-offset-4">
						<h5>COPYRIGHT 2016 © MEDIATUCH.COM</h5>
					</div>
				</div>
			</div>	
		</footer> 
	</body>
</html>

