<div class="page-title">
  <div class="vague2"></div>
  <div class="container">
  	<h2 class="title">événementiel</h2>
  </div>
</div>
<div class="content eventdetail">
  <div class="container">
  	<div class="col-lg-12">
  		<img src="images/events.gif" width="100%" />
  	</div>
  	<div class="col-lg-12 desc">
  		<p>Créé en 2014 MEDIA TUCH est une agence de communication et événementiel dont l’activité est dédiée à la conception et la mise en œuvre de projets évènementiels et de communication responsables à destination des entreprises et des collectivités.</p>
		<p>Grâce à son équipe jeune, pluridisciplinaire, dynamique et créative, MEDIA TUCH propose une gestion efficace et novatrice de vos besoins en communication. Elle vous accompagne dans la réussite de vos enjeux.</p>
  	</div>
  </div>
  <div class="container">
  	<div class="col-lg-12">
  		<h5>Sur le même sujet...</h5>
  	</div>
  </div>
</div>

