<div class="page-title">
  <div class="vague2"></div>
  <div class="container">
  	<h2 class="title">About us</h2>
  </div>
</div>
<div class="content">
  <div class="container">
  	<div class="col-lg-6">
  		<iframe width="100%" height="315" src="https://www.youtube.com/embed/ALrLuom_n94" frameborder="0" allowfullscreen></iframe>
  	</div>
  	<div class="col-lg-6">
  		<p>Créé en 2014 MEDIA TUCH est une agence de communication et événementiel dont l’activité est dédiée à la conception et la mise en œuvre de projets évènementiels et de communication responsables à destination des entreprises et des collectivités.</p>
  		<p>Grâce à son équipe jeune, pluridisciplinaire, dynamique et créative, MEDIA TUCH propose une gestion efficace et novatrice de vos besoins en communication. Elle vous accompagne dans la réussite de vos enjeux.</p>
		<p>Le savoir faire de nos équipes et notre motivation de tous les instants nous permettent d'orchestrer l'ensemble des techniques de communication.
  		</p>
  	</div>
  </div>
  <div class="container">
  	<h3>NOTRE APPROCHE</h3>
  	<div class="col-lg-6">
  		<h4>L'ENGAGEMENT</h4>
  		<p>Engagement dans la réalisation de vos objectifs de communication, engagement à anticiper vos besoins et, surtout, engagement de nos créatifs et chefs de projets à vos côtés.</p>
  	</div>
  	<div class="col-lg-6">
  		<h4>LA CONFIANCE</h4>
  		<p>Les relations avec nos clients, considérés comme de véritables partenaires, sont basées sur la confiance : confiance sur la compétence de nos équipes, confiance sur les prestations facturées et confiance sur la fiabilité des délais.</p>
  	</div>
  </div>
  <div class="container">
  	<div class="col-lg-6">
  		<h4>LA RÉACTIVITÉ</h4>
  		<p>Vos contraintes de timing et budgétaires évoluent et sont toujours plus pressantes, nous nous attachons au quotidien à réagir au plus vite à vos demandes. Une équipe de créatifs est spécialement dédiée à la réalisation de vos urgences.</p>
  	</div>
  	<div class="col-lg-6">
  		<h4>LA FLEXIBILITÉ</h4>
  		<p>La communication n'est pas une science exacte, conscient de vos contraintes et impératifs, vos commentaires et corrections sont toujours les bienvenus.</p>
  	</div>
  </div>
  <div class="container">
  	<div class="col-lg-6">
  		<h4>L'ENGAGEMENT</h4>
  		<p>Engagement dans la réalisation de vos objectifs de communication, engagement à anticiper vos besoins et, surtout, engagement de nos créatifs et chefs de projets à vos côtés.</p>
  	</div>
  	<div class="col-lg-6">
  		<h4>LA TRANSPARENCE</h4>
  		<p>Nous accordons une attention particulière à vous communiquer avec une parfaite transparence les budgets correspondants aux prestations réalisées. Vous disposez ainsi pour chaque opération d'une vision claire et détaillée.</p>
  	</div>
  </div>
</div>

