<div class="page-title">
  <div class="vague2"></div>
  <div class="container">
  	<h2 class="title">PORTFOLIO</h2>
  </div>
</div>
<div class="content portfolio">
  <div class="container">
  	<div id="filters" class="button-group">  <button class="button is-checked" data-filter="*">Tout</button>
      <button class="button" data-filter=".identityvisual">Identité Visuelle & logo</button>
      <button class="button" data-filter=".web">Site Web</button>
      <button class="button" data-filter=".application">Application</button>
      <button class="button" data-filter=".impression">Impression</button>
    </div>
    <div class="isotope">
      <div class="element-item web col-lg-3 view view-sixth" data-category="web">
        <img src="images/videos/video1.jpg" />
        <div class="mask">  
          <h2>BADR SOULTAN</h2>  
          <p>Client: UNIVERSAL<br/>Date de réalisation : 05/2014<br/>Pays : Maroc</p>  
          <a href="https://www.youtube.com/watch?v=KGG-C2UCVvQ" data-action="watch-video" class="info"><i class="fa fa-play" aria-hidden="true"></i></a>  
        </div>  
      </div>
      <div class="element-item identityvisual col-lg-3 view view-sixth" data-category="identityvisual">
        <img src="images/videos/video2.jpg" />
        <div class="mask">  
          <h2>BADR SOULTAN</h2>  
          <p>Date de réalisation : 05/2014<br/>Pays : Maroc</p>  
          <a target="_blank" href="https://www.youtube.com/watch?v=KGG-C2UCVvQ" class="info"><i class="fa fa-play" aria-hidden="true"></i></a>  
        </div>  
      </div>
      <div class="element-item web col-lg-3 view view-sixth" data-category="web">
        <img src="images/videos/video3.jpg" />
        <div class="mask">  
          <h2>BADR SOULTAN</h2>  
          <p>Date de réalisation : 05/2014<br/>Pays : Maroc</p>  
          <a target="_blank" href="https://www.youtube.com/watch?v=wrhvWD_g1hI" class="info"><i class="fa fa-play" aria-hidden="true"></i></a>  
        </div>  
      </div>
      <div class="element-item application col-lg-3 view view-sixth" data-category="application">
        <img src="images/videos/video4.jpg" />
        <div class="mask">  
          <h2>BADR SOULTAN</h2>  
          <p>Date de réalisation : 05/2014<br/>Pays : Maroc</p>  
          <a target="_blank" href="https://www.youtube.com/watch?v=KGG-C2UCVvQ" class="info"><i class="fa fa-play" aria-hidden="true"></i></a>  
        </div>  
      </div>
      <div class="element-item identityvisual col-lg-3 view view-sixth" data-category="identityvisual">
        <img src="images/videos/video5.jpg" />
        <div class="mask">  
          <h2>BADR SOULTAN</h2>  
          <p>Date de réalisation : 05/2014<br/>Pays : Maroc</p>  
          <a target="_blank" href="https://www.youtube.com/watch?v=KGG-C2UCVvQ" class="info"><i class="fa fa-play" aria-hidden="true"></i></a>  
        </div>  
      </div>
      <div class="element-item impression col-lg-3 view view-sixth" data-category="impression">
        <img src="images/videos/video6.jpg" />
        <div class="mask">  
          <h2>BADR SOULTAN</h2>  
          <p>Date de réalisation : 05/2014<br/>Pays : Maroc</p>  
          <a target="_blank" href="https://www.youtube.com/watch?v=KGG-C2UCVvQ" class="info"><i class="fa fa-play" aria-hidden="true"></i></a>  
        </div>  
      </div>
      <div class="element-item identityvisual col-lg-3 view view-sixth" data-category="identityvisual">
        <img src="images/videos/video7.jpg" />
        <div class="mask">  
          <h2>BADR SOULTAN</h2>  
          <p>Date de réalisation : 05/2014<br/>Pays : Maroc</p>  
          <a target="_blank" href="https://www.youtube.com/watch?v=KGG-C2UCVvQ" class="info"><i class="fa fa-play" aria-hidden="true"></i></a>  
        </div>  
      </div>
      <div class="element-item impression col-lg-3 view view-sixth" data-category="impression">
        <img src="images/videos/video8.jpg" />
        <div class="mask">  
          <h2>BADR SOULTAN</h2>  
          <p>Date de réalisation : 05/2014<br/>Pays : Maroc</p>  
          <a target="_blank" href="https://www.youtube.com/watch?v=KGG-C2UCVvQ" class="info"><i class="fa fa-play" aria-hidden="true"></i></a>  
        </div>  
      </div>
      <div class="element-item impression col-lg-3 view view-sixth" data-category="impression">
        <img src="images/videos/video9.jpg" />
        <div class="mask">  
          <h2>BADR SOULTAN</h2>  
          <p>Date de réalisation : 05/2014<br/>Pays : Maroc</p>  
          <a target="_blank" href="https://www.youtube.com/watch?v=KGG-C2UCVvQ" class="info"><i class="fa fa-play" aria-hidden="true"></i></a>  
        </div>  
      </div>
      <div class="element-item web col-lg-3 view view-sixth" data-category="web">
        <img src="images/videos/video10.jpg" />
        <div class="mask">  
          <h2>BADR SOULTAN</h2>  
          <p>Date de réalisation : 05/2014<br/>Pays : Maroc</p>  
          <a target="_blank" href="https://www.youtube.com/watch?v=KGG-C2UCVvQ" class="info"><i class="fa fa-play" aria-hidden="true"></i></a>  
        </div>  
      </div>
      
    </div> 
  </div>
</div>


<script>
    "use strict";

    $(document).ready(function () {
    
      //each video has need its own instance of modalVideoOptions  
      $('a[href]').each(function(){
        $(this).modalvideo(new ModalVideoOptions());
      });
    });
</script>





