<div class="page-title">
  <div class="vague2"></div>
  <div class="container">
  	<h2 class="title">CONTACT</h2>
  </div>
</div>
<div class="content contact">
  <div class="Container">
	 <div class="col-lg-8">
	 	<h2>Obtenez une prescription !</h2>
	 	<p>Vous souhaitez obtenir une prescription ?<br/>
		N’hésitez pas à remplir le formulaire ci-dessous, nous tâcherons de vous répondre rapidement.</p>
		<h4>COORDONNÉES DU PATIENT</h4>
		<div class="col-lg-6 ticket">
			<p class="ticket">Nom <span>*</span></p>
			<input class="col-lg-12" type="text" id="nom" />
		</div>
		<div class="col-lg-6 ticket">
			<p>Prénom <span>*</span></p>
			<input class="col-lg-12" type="text" id="prenom" />
		</div>
		<div class="col-lg-6 ticket">
			<p class="ticket">Société</p>
			<input class="col-lg-12" type="text" id="ste" />
		</div>
		<div class="col-lg-6 ticket">
			<p>Email <span>*</span></p>
			<input class="col-lg-12" type="text" id="email" />
		</div>
		<div class="col-lg-12 ticket">
			<p>Adresse</p>
			<input class="col-lg-12" type="text" id="adress" />
		</div>
		<div class="col-lg-6 ticket">
			<p class="ticket">Ville</p>
			<input class="col-lg-12" type="text" id="ville" />
		</div>
		<div class="col-lg-6 ticket">
			<p>ZIP / Code Postal</p>
			<input class="col-lg-12" type="text" id="zip" />
		</div>
		<div class="col-lg-6 ticket">
			<p>Téléphone</p>
			<input class="col-lg-12" type="text" id="tel" />
		</div>
		<h4 class="col-lg-12">DIAGNOSTIC</h4>
		<div class="col-lg-12 ticket">
			<p>Sujet <span>*</span> <em><span style="font-size: 12px; color: #717375; font-weight: normal;">(Veuillez choisir le sujet de votre message)</span></em></p>
			<div class="col-lg-3 casecocher">
				<input type="checkbox" name="devis" id="devis">
				<label for="devis">Demande de devis</label>
			</div>
			<div class="col-lg-3 casecocher">
				<input type="checkbox" name="devis" id="devis">
				<label for="devis">Demande de stage</label>
			</div>
			<div class="col-lg-3 casecocher">
				<input type="checkbox" name="devis" id="devis">
				<label for="devis">Demande d'emploi</label>
			</div>
			<div class="col-lg-3 casecocher">
				<input type="checkbox" name="devis" id="devis">
				<label for="devis">Autre</label>
			</div>
		</div>
		<h4 class="col-lg-12">VOTRE MESSAGE</h4>
		<div class="col-lg-12 ticket">
			<p>Message <span>*</span></p>
			<textarea class="col-lg-12" rows="10" type="text" id="message"></textarea>
		</div>
		<div class="col-lg-3 ticket">
			<input class="col-lg-12" type="button" id="submit" value="Envoyer"/>
		</div>
	 </div>  
	 <div class="col-lg-4 coord">
	 	<h2>Nos coordonnées</h2>
	 	<span class="col-lg-2"><img src="images/mapicon.png" /></span>
	 	<p class="col-lg-10">Imm A 23, N° 10, EL Mansour 3, 50050 Meknes - Maroc</p>
	 	<span class="col-lg-2"><img src="images/telicon.png" /></span>
	 	<p class="col-lg-10">+ 212 645 756 139 <br/>
		+ 212 663 614 679</p>
	 	<span class="col-lg-2"><img src="images/registreicon.png" /></span>
	 	<p class="col-lg-10">N° RC : 37193
		<br>N° de patente : 62295273
		<br>N° identifiant fiscal : 151664267
		<br>N° affiliation à la CNSS : 9934622</p>
	 	<span class="col-lg-2"><img src="images/compteicon.png" /></span>
	 	<p class="col-lg-10" style="margin-bottom: 20px;">Nom : STE MEDIA TUCH
		<br>Nom de banque : SOCIETE GENERALE MAROCAINE DE BANQUE
		<br>Adresse de la banque : Place Al Wahda Al Ifriquia - MEKNES
		<br>R.I.B : 022480000081002780476702
		<br>IBAN : MA022480000081002780476702
		<br>Code SWIFT : SGMB MAMC XXX</p>
	 </div>	
  </div>
</div>

